const colors = {
  light: {
    text: "#F8F8FF",
    tint: "#7C3AED",
    background: "#0A0A0F",
    foreground: "#F8F8FF",
    card: "#1C1C27",
    cardForeground: "#F8F8FF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#13131A",
    secondaryForeground: "#F8F8FF",
    muted: "#13131A",
    mutedForeground: "#9B9BB4",
    accent: "#7C3AED",
    accentSecondary: "#06B6D4",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A3D",
    input: "#1C1C27",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
  },
  dark: {
    text: "#F8F8FF",
    tint: "#7C3AED",
    background: "#0A0A0F",
    foreground: "#F8F8FF",
    card: "#1C1C27",
    cardForeground: "#F8F8FF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#13131A",
    secondaryForeground: "#F8F8FF",
    muted: "#13131A",
    mutedForeground: "#9B9BB4",
    accent: "#7C3AED",
    accentSecondary: "#06B6D4",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A3D",
    input: "#1C1C27",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
  },
  radius: 12,
};

export default colors;
